### ISSUE TITLE
Quick Tagging error

### ISSUE THREAD

**Issue by dedu6ka** [Arthur-Milchior/Quick_Tagging#5]
Link to reddit; i addressed it to ijgnord.
https://www.reddit.com/r/Anki/comments/epdrpr/quick_tagging/

**Comment by Arthur-Milchior** [comment]
Sorry. I really can't understand what you are saying.
I tried to read the reddit link and can't make any sens of it. 
@ijgnord correctly told you what was wrong with the json. Is there anything else you want to know ?

Otherwise, please be precise. What is the bug you have ? What are you trying to do, and what occurs instead. What version of anki do you currently use ?

**Comment by dedu6ka** [comment]
I edited my old post:   
 Anki 2.1
The error message is here-> http://prntscr.com/qoc3eg
 1.  I like your default :FailedOverdue tag !   
 2.  Can you put the tag "Interferes" in one of the examples?
 3. Can you add the  action   "Move to  Deck "Retire"  after rating the card? 
 
 > @ijgnord correctly told you what was wrong with the json. Is there anything else you want to know ?  
I am not curious about the reason for error. As the OP said - can the add-on be fixed for everyone? 
Thank you.

**Comment by ijgnd** [comment]
I just ocr'ed dedu6ka screenshot. @dedu6ka: your annotated screenshots are very useful. It would be easier to communicate back the solution for config files if you could additionally post the config as text so that I can just copy and edit it. Maybe my OCR misread one character in some config name or tag so that you get weird behavior with the following solution..

try this:

    {
        "add tag shortcut": "q",
        "edit tag shortcut": "w",
        "quick tags": {
            "Shift+E": {
                "action": "suspend",
                "tags": "FailedOdue"
            },
            "Shift+L": {
                "action": "bury card",
                "tags": "FailedOdue"
            }
        },
        "tag shortcut": "q"
    }   

I changed your

        }
    },
         "Shift+L": {

into

        },
        "Shift+L": {

So my first answer was imprecise and thus incorrect. You just need to remove one "}"  - I should have also checked the line on top of it and noticed that it doesn't end with a "," ...

**Comment by dedu6ka** [comment]
Everything works - thank you.  
Can you put it on the web?

**Comment by ijgnd** [comment]
@dedu6ka: I don't understand. What do you mean? where? Do you mean update the ankiweb listing. If so, what's wrong with the current default config of "quick tagging"?

**Comment by dedu6ka** [comment]
@ijgnord
The web version produced the error - you saw it.  
I am going to check it now.

**Comment by dedu6ka** [comment]
@ijgnord 
It works. Thanks a lot for your patience.

**Comment by dedu6ka** [comment]
@ijgnord
I changed the tag 'overdue' to 'retire' ( one coupled with 'Suspend');  
reopened Anki --> Shift+E.  The tag was 'there' but the card was not suspended.  
In config I restored default and it restored the old config - see below.
{
    "add tag shortcut": "q",
    "edit tag shortcut": "w",
    "quick tags": {
        "Ctrl+Shift+B": {
            "action": "bury note",
            "tags": "ExampleOfBuriedNote"
        },
        "Shift+B": {
            "action": "bury card",
            "tags": "ExampleOfBuriedCard"
        },
        "Shift+N": {
            "tags": "ExampleOfTagNothing"
        },
        "Shift+S": {
            "action": "suspend card",
            "tags": "ExampleOfSuspend"
        }
    }
}

I closed config and reopened it right away and !!! the correct config showed up.

**Comment by ijgnd** [comment]
@dedu6ka: 

Your config doesn't match the default config. the default config uses `"action": "suspend card",` whereas you have `"action": "suspend",`.  The readme on the right side contains an error. I will change this.

&nbsp;

You should really use proper markdown formatting which makes it much easier to read your code.

in Markdown blocks of code are either fenced by lines with three back-ticks ```, or are indented with four spaces. (in the old reddit interface only indenting each line by four spaces works ...)

**Comment by dedu6ka** [comment]
I deleted the add-on; downloaded it and it works.  
What is different from the previous re-download - i was not deleting the existing add-on.  The config i see now :  
'''
{
    "add tag shortcut": "q",
    "edit tag shortcut": "w",
    "quick tags": {
        "Ctrl+Shift+B": {
            "action": "bury note",
            "tags": "ExampleOfBuriedNote"
        },
        "Shift+B": {
            "action": "bury card",
            "tags": "ExampleOfBuriedCard"
        },
        "Shift+N": {
            "tags": "ExampleOfTagNothing"
        },
        "Shift+S": {
            "action": "suspend card",
            "tags": "ExampleOfSuspend"
        }
    }
}
'''

**Comment by ijgnd** [comment]
could you edit your post so that it's formatted as code. Before you publish a post you can check the preview on github. Since yours is not formatted as code there's no indentation and comparing is much harder.

in markdown instead of the regular apostrophe key you need to use the grave accent key to surround code, see https://en.wikipedia.org/wiki/Grave_accent#Use_in_programming

**Comment by Arthur-Milchior** [comment]
"Can you put the tag "Interferes" in one of the examples?"
Why do you want that ? I mean, you can add any tags you want in the config. You don't need me to add any specific tags.

"Move to Deck "Retire" after rating the card?"
You mean that, you want a button which, when you press it, does nothing but wait for you to click on easy/hard/good, and once it's pressed, move the card to another deck ?
Sorry, but I won't do it.
Currently, the add-on acts immediately. Dealing with delayed action is far more complex. Because I would need to remember what you are supposed to do, I would need to change the action occurring when you review the card. I would need to figure out what to do if you leave the reviewer and come back. I would also need to add a way for users to cancel this rule.  Those are a lot of complex things I don't want to add in this add-on. It may be part of another add-on, but I'd ask to be payed to create it.
