### ISSUE TITLE
Stopped working after update on 02-10-2020

### ISSUE THREAD

**Issue by lawsont96** [Arthur-Milchior/Quick_Tagging#7]
Previous to updating earlier today it had been working wonderfully but afterwards it completely ceased functioning. I tried disabling every other add-on I had (every single other one was simultaneously disabled with only quick tagging enabled) to make sure there wasn't some new hotkey interference I didn't notice, I tried restarted Anki several times to be sure, changing the hotkey around (I only use it for one action set) and nothing worked. This add-on was very helpful previously so I hope the issue gets resolved soon but it seems to be intrinsic as I attemped to isolate it as much as possible and it continued to be non-functional.

**Comment by lawsont96** [comment]
Also, for further clarification, when I attempted changing my hotkey around I had first verified that I was changing to a hotkey that was not already in use. In addition, just now I attempted to use the built-in hotkeys (the examples that come with the add-on) and they no longer work either.

**Comment by Arthur-Milchior** [comment]
Thank you for letting me know.
Can you please tell me: do you have an error message, or does it just do nothing ?
Can you please tell me which version of anki you use ?

**Comment by lawsont96** [comment]
It's just doing nothing. There's no error message or anything like that, it's more just that it's like the add-on isn't installed. I'm on v2.1.19

**Comment by Arthur-Milchior** [comment]
I found the problem. I wonder why you are the first one to report it, while it probably did occur to every single user. 
If you are technically inclined, my error was to think that the shortcut hook was a filter. That is, instead of appending the new shortcuts to the list of shortcuts I was creating and returning a new list. 

The change was currently useless, as you stated, the add-on was already working fine before. I just was trying to ensure that the add-on remains with the future version of anki; because Damien (Anki's creator) is trying to change the methods add-on works. Privileging hooks and filtering and wanting to avoid monkey patching.

Since the add-on seems useful to you, can you maybe think about leaving a tip ? https://ko-fi.com/arthurmilchior
If the problem is indeed corrected, please close the issue

**Comment by WickedCheese18** [comment]
Interesting, I appreciate the explanation of what went wrong, I enjoy seeing what's going on in the background. It looks to be working now, thank you for the patch!
